### ISSUE TITLE
I try to make another column but its not working. 

### ISSUE THREAD

**Issue by jahir07** [akhil110/Todo-App#2]
Here is the code-- todo-service.js

tx.executeSql("CREATE TABLE IF NOT EXISTS tasks (task_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, task_name VARCHAR(100), task_content VARCHAR(500) )",[]);

function setTasks(tname, tcontent){
return promisedQuery("INSERT INTO tasks(task_name, task_content) VALUES ('" + tname +  "," + tcontent +  "') ", defaultResultHandler, defaultErrorHandler);
}

set: function(t_name, t_content) {
    return setTasks(t_name, t_content);
},

In todo.js

  // Called when the form is submitted
  $scope.createTask = function(task) {
    SQLService.set(task.title, task.content);
    $scope.loadTask();
    $scope.taskModal.hide();
    task.title = "";
  };

but not working??
by the way how can i delete sqlite database.

**Comment by akhil110** [comment]
Hi,

Please use the below code and it will work now. Please do proper error
handling to see the error details.

function setTasks(tname, tcontent){
    return promisedQuery("INSERT INTO tasks(task_name, task_content)
VALUES ('" + tname +  "','" + tcontent +  "') ", defaultResultHandler,
defaultErrorHandler);
}

On Wed, Apr 29, 2015 at 8:46 AM, jahir07 notifications@github.com wrote:

> Here is the code-- todo-service.js
> function createDB() {
> try {
> db = window.openDatabase("todoDB", "1.0", "ToDoApp", 10_1024_1024);
> db.transaction(function(tx){
> tx.executeSql("CREATE TABLE IF NOT EXISTS tasks (task_id INTEGER NOT NULL
> PRIMARY KEY AUTOINCREMENT, task_name VARCHAR(100), task_content
> VARCHAR(500) )",[]);
> 
> ```
>     });
> } catch (err) {
>     alert("Error processing SQL: " + err);
> }
> console.log('database created');
> ```
> 
> }
> 
> function setTasks(tname, tcontent){
>     return promisedQuery("INSERT INTO tasks(task_name, task_content) VALUES ('" + tname +  "," + tcontent +  "') ", defaultResultHandler, defaultErrorHandler);
> }
> 
> ....
> 
> return {
> setup: function() {
> return createDB();
> },
> set: function(t_name, t_content) {
> return setTasks(t_name, t_content);
> },
> del: function(taskid) {
> return delTasks(taskid);
> },
> edit: function(t_name,taskid) {
> return UpdateTasks(t_name, taskid);
> },
> all: function() {
> return getTasks();
> }
> }
> 
> In todo.js
> 
> // Called when the form is submitted
> $scope.createTask = function(task) {
> SQLService.set(task.title, task.content);
> $scope.loadTask();
> $scope.taskModal.hide();
> task.title = "";
> };
> 
> but now working??
> by the way how can i delete sqlite database.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akhil110/Todo-App/issues/2.

## 

Regards,

Akhilesh Srivastava

**Comment by jahir07** [comment]
Thanks its working now.. thanks a lot.. :)
